title: aezi's tales
author: aezi
email: aether@aezlo.com
description: > # this means to ignore newlines until "show_exerpts:"
  My Blog in general, there is everything to anything and more - you will see...
show_excerpts: true # set to true to show excerpts on the homepage
url: http://gravite.aezlo.com
baseurl: #

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Aezi
  tagline: Coder, Football, Man City
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: hide
  disqus_shortname: gravite

  # generate social links in footer
  social_links:
    twitter: aezl21
    github:  minichest
    linkedIn: #
    rss: #
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed